# Branch Protection Configuration
# This file defines branch protection rules for GitHub repository
# Apply using GitHub CLI: gh api repos/:owner/:repo/branches/main/protection --method PUT --input branch-protection.yml

main:
  required_status_checks:
    strict: true
    contexts:
      - "ci/test"
      - "ci/lint"
      - "ci/security"
      - "ci/build"
  enforce_admins: true
  required_pull_request_reviews:
    required_approving_review_count: 2
    dismiss_stale_reviews: true
    require_code_owner_reviews: true
    require_last_push_approval: true
  restrictions:
    users: []
    teams: ["core-maintainers", "senior-developers"]
  allow_force_pushes: false
  allow_deletions: false
  block_creations: false

develop:
  required_status_checks:
    strict: true
    contexts:
      - "ci/test"
      - "ci/lint"
  enforce_admins: false
  required_pull_request_reviews:
    required_approving_review_count: 1
    dismiss_stale_reviews: true
    require_code_owner_reviews: true
    require_last_push_approval: false
  restrictions:
    users: []
    teams: ["developers", "core-maintainers"]
  allow_force_pushes: false
  allow_deletions: false
  block_creations: false
# Commands to apply protection rules:
# gh api repos/DevilsDev/rag-pipeline-utils/branches/main/protection --method PUT --field required_status_checks='{"strict":true,"contexts":["ci/test","ci/lint","ci/security","ci/build"]}' --field enforce_admins=true --field required_pull_request_reviews='{"required_approving_review_count":2,"dismiss_stale_reviews":true,"require_code_owner_reviews":true}' --field restrictions='{"users":[],"teams":["core-maintainers"]}' --field allow_force_pushes=false --field allow_deletions=false

# gh api repos/DevilsDev/rag-pipeline-utils/branches/develop/protection --method PUT --field required_status_checks='{"strict":true,"contexts":["ci/test","ci/lint"]}' --field enforce_admins=false --field required_pull_request_reviews='{"required_approving_review_count":1,"dismiss_stale_reviews":true,"require_code_owner_reviews":true}' --field restrictions='{"users":[],"teams":["developers","core-maintainers"]}' --field allow_force_pushes=false --field allow_deletions=false
